org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.parallel=true
android.useAndroidX=true
android.builder.sdkDownload=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx4G
cmake.dir=/Users/eva/Library/Android/sdk/cmake/3.22.1
