org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.builder.sdkDownload=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx4G
cmake.dir=/Users/eva/Desktop/Project/MobileApp/android/cmake/cmake-3.22.1-macos-universal/CMake.app/Contents
GETUI_APPID=mEThFmzDwk623y4GUeyzZ1